vim.cmd("hi clear")

if vim.fn.exists("syntax_on") == 1 then
	vim.cmd("syntax reset")
end

vim.g.colors_name = "old-faithful"

local palette = require("old-faithful.palette")
local c = palette.colors

local function hi(name, hl)
	vim.api.nvim_set_hl(0, name, hl)
end

-- Highlight groups shared by Neovim's light and dark defaults.
local function apply_common_highlights()
	hi("@attribute", { link = "Macro" })
	hi("@attribute.builtin", { link = "Special" })
	hi("@boolean", { link = "Boolean" })
	hi("@character", { link = "Character" })
	hi("@character.special", { link = "SpecialChar" })
	hi("@comment", { link = "Comment" })
	hi("@comment.error", { link = "DiagnosticError" })
	hi("@comment.note", { link = "DiagnosticInfo" })
	hi("@comment.todo", { link = "Todo" })
	hi("@comment.warning", { link = "DiagnosticWarn" })
	hi("@constant", { link = "Constant" })
	hi("@constant.builtin", { link = "Special" })
	hi("@constructor", { link = "Special" })
	hi("@diff.delta", { link = "Changed" })
	hi("@diff.minus", { link = "Removed" })
	hi("@diff.plus", { link = "Added" })
	hi("@function", { link = "Function" })
	hi("@function.builtin", { link = "Special" })
	hi("@keyword", { link = "Keyword" })
	hi("@label", { link = "Label" })
	hi("@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
	hi("@lsp.type.class", { link = "@type" })
	hi("@lsp.type.comment", { link = "@comment" })
	hi("@lsp.type.decorator", { link = "@attribute" })
	hi("@lsp.type.enum", { link = "@type" })
	hi("@lsp.type.enumMember", { link = "@constant" })
	hi("@lsp.type.event", { link = "@type" })
	hi("@lsp.type.function", { link = "@function" })
	hi("@lsp.type.interface", { link = "@type" })
	hi("@lsp.type.keyword", { link = "@keyword" })
	hi("@lsp.type.macro", { link = "@constant.macro" })
	hi("@lsp.type.method", { link = "@function.method" })
	hi("@lsp.type.modifier", { link = "@type.qualifier" })
	hi("@lsp.type.namespace", { link = "@module" })
	hi("@lsp.type.number", { link = "@number" })
	hi("@lsp.type.operator", { link = "@operator" })
	hi("@lsp.type.parameter", { link = "@variable.parameter" })
	hi("@lsp.type.property", { link = "@property" })
	hi("@lsp.type.regexp", { link = "@string.regexp" })
	hi("@lsp.type.string", { link = "@string" })
	hi("@lsp.type.struct", { link = "@type" })
	hi("@lsp.type.type", { link = "@type" })
	hi("@lsp.type.typeParameter", { link = "@type.definition" })
	hi("@lsp.type.variable", { link = "@variable" })
	hi("@markup", { link = "Special" })
	hi("@markup.heading", { link = "Title" })
	hi("@markup.italic", { cterm = { italic = true }, italic = true })
	hi("@markup.link", { link = "Underlined" })
	hi("@markup.strikethrough", { cterm = { strikethrough = true }, strikethrough = true })
	hi("@markup.strong", { cterm = { bold = true }, bold = true })
	hi("@markup.underline", { cterm = { underline = true }, underline = true })
	hi("@module", { link = "Structure" })
	hi("@module.builtin", { link = "Special" })
	hi("@number", { link = "Number" })
	hi("@number.float", { link = "Float" })
	hi("@operator", { link = "Operator" })
	hi("@property", { link = "Identifier" })
	hi("@punctuation", { link = "Delimiter" })
	hi("@punctuation.special", { link = "Special" })
	hi("@string", { link = "String" })
	hi("@string.escape", { link = "@string.special" })
	hi("@string.regexp", { link = "@string.special" })
	hi("@string.special", { link = "SpecialChar" })
	hi("@string.special.url", { link = "Underlined" })
	hi("@tag", { link = "Tag" })
	hi("@tag.builtin", { link = "Special" })
	hi("@type", { link = "Type" })
	hi("@type.builtin", { link = "Special" })
	hi("@variable.builtin", { link = "Special" })
	hi("@variable.parameter.builtin", { link = "Special" })
	hi("Boolean", { link = "Constant" })
	hi("Character", { link = "Constant" })
	hi("ComplHint", { link = "NonText" })
	hi("ComplHintMore", { link = "MoreMsg" })
	hi("ComplMatchIns", {  })
	hi("Conditional", { link = "Statement" })
	hi("CursorIM", { link = "Cursor" })
	hi("CursorLineFold", { link = "FoldColumn" })
	hi("CursorLineNr", { cterm = { bold = true }, bold = true })
	hi("CursorLineSign", { link = "SignColumn" })
	hi("Debug", { link = "Special" })
	hi("Define", { link = "PreProc" })
	hi("DiagnosticFloatingError", { link = "DiagnosticError" })
	hi("DiagnosticFloatingHint", { link = "DiagnosticHint" })
	hi("DiagnosticFloatingInfo", { link = "DiagnosticInfo" })
	hi("DiagnosticFloatingOk", { link = "DiagnosticOk" })
	hi("DiagnosticFloatingWarn", { link = "DiagnosticWarn" })
	hi("DiagnosticSignError", { link = "DiagnosticError" })
	hi("DiagnosticSignHint", { link = "DiagnosticHint" })
	hi("DiagnosticSignInfo", { link = "DiagnosticInfo" })
	hi("DiagnosticSignOk", { link = "DiagnosticOk" })
	hi("DiagnosticSignWarn", { link = "DiagnosticWarn" })
	hi("DiagnosticUnnecessary", { link = "Comment" })
	hi("DiagnosticVirtualLinesError", { link = "DiagnosticError" })
	hi("DiagnosticVirtualLinesHint", { link = "DiagnosticHint" })
	hi("DiagnosticVirtualLinesInfo", { link = "DiagnosticInfo" })
	hi("DiagnosticVirtualLinesOk", { link = "DiagnosticOk" })
	hi("DiagnosticVirtualLinesWarn", { link = "DiagnosticWarn" })
	hi("DiagnosticVirtualTextError", { link = "DiagnosticError" })
	hi("DiagnosticVirtualTextHint", { link = "DiagnosticHint" })
	hi("DiagnosticVirtualTextInfo", { link = "DiagnosticInfo" })
	hi("DiagnosticVirtualTextOk", { link = "DiagnosticOk" })
	hi("DiagnosticVirtualTextWarn", { link = "DiagnosticWarn" })
	hi("DiffTextAdd", { link = "DiffText" })
	hi("EndOfBuffer", { link = "NonText" })
	hi("Exception", { link = "Statement" })
	hi("Float", { link = "Number" })
	hi("FloatBorder", { link = "NormalFloat" })
	hi("FloatFooter", { link = "FloatTitle" })
	hi("FloatTitle", { link = "Title" })
	hi("FoldColumn", { link = "SignColumn" })
	hi("Ignore", { link = "Normal" })
	hi("IncSearch", { link = "CurSearch" })
	hi("Include", { link = "PreProc" })
	hi("Keyword", { link = "Statement" })
	hi("Label", { link = "Statement" })
	hi("LineNrAbove", { link = "LineNr" })
	hi("LineNrBelow", { link = "LineNr" })
	hi("LspCodeLens", { link = "NonText" })
	hi("LspCodeLensSeparator", { link = "LspCodeLens" })
	hi("LspInlayHint", { link = "NonText" })
	hi("LspReferenceRead", { link = "LspReferenceText" })
	hi("LspReferenceTarget", { link = "LspReferenceText" })
	hi("LspReferenceText", { link = "Visual" })
	hi("LspReferenceWrite", { link = "LspReferenceText" })
	hi("LspSignatureActiveParameter", { link = "Visual" })
	hi("Macro", { link = "PreProc" })
	hi("MsgArea", {  })
	hi("MsgSeparator", { link = "StatusLine" })
	hi("NormalNC", {  })
	hi("Number", { link = "Constant" })
	hi("NvimAnd", { link = "NvimBinaryOperator" })
	hi("NvimArrow", { link = "Delimiter" })
	hi("NvimAssignment", { link = "Operator" })
	hi("NvimAssignmentWithAddition", { link = "NvimAugmentedAssignment" })
	hi("NvimAssignmentWithConcatenation", { link = "NvimAugmentedAssignment" })
	hi("NvimAssignmentWithSubtraction", { link = "NvimAugmentedAssignment" })
	hi("NvimAugmentedAssignment", { link = "NvimAssignment" })
	hi("NvimBinaryMinus", { link = "NvimBinaryOperator" })
	hi("NvimBinaryOperator", { link = "NvimOperator" })
	hi("NvimBinaryPlus", { link = "NvimBinaryOperator" })
	hi("NvimCallingParenthesis", { link = "NvimParenthesis" })
	hi("NvimColon", { link = "Delimiter" })
	hi("NvimComma", { link = "Delimiter" })
	hi("NvimComparison", { link = "NvimBinaryOperator" })
	hi("NvimComparisonModifier", { link = "NvimComparison" })
	hi("NvimConcat", { link = "NvimBinaryOperator" })
	hi("NvimConcatOrSubscript", { link = "NvimConcat" })
	hi("NvimContainer", { link = "NvimParenthesis" })
	hi("NvimCurly", { link = "NvimSubscript" })
	hi("NvimDict", { link = "NvimContainer" })
	hi("NvimDivision", { link = "NvimBinaryOperator" })
	hi("NvimDoubleQuote", { link = "NvimStringQuote" })
	hi("NvimDoubleQuotedBody", { link = "NvimStringBody" })
	hi("NvimDoubleQuotedEscape", { link = "NvimStringSpecial" })
	hi("NvimDoubleQuotedUnknownEscape", { link = "NvimInvalidValue" })
	hi("NvimEnvironmentName", { link = "NvimIdentifier" })
	hi("NvimEnvironmentSigil", { link = "NvimOptionSigil" })
	hi("NvimFigureBrace", { link = "NvimInternalError" })
	hi("NvimFloat", { link = "NvimNumber" })
	hi("NvimIdentifier", { link = "Identifier" })
	hi("NvimIdentifierKey", { link = "NvimIdentifier" })
	hi("NvimIdentifierName", { link = "NvimIdentifier" })
	hi("NvimIdentifierScope", { link = "NvimIdentifier" })
	hi("NvimIdentifierScopeDelimiter", { link = "NvimIdentifier" })
	hi("NvimInternalError", { fg = "#ff0000", bg = "#ff0000", ctermfg = 9, ctermbg = 9 })
	hi("NvimInvalid", { link = "Error" })
	hi("NvimInvalidAnd", { link = "NvimInvalidBinaryOperator" })
	hi("NvimInvalidArrow", { link = "NvimInvalidDelimiter" })
	hi("NvimInvalidAssignment", { link = "NvimInvalid" })
	hi("NvimInvalidAssignmentWithAddition", { link = "NvimInvalidAugmentedAssignment" })
	hi("NvimInvalidAssignmentWithConcatenation", { link = "NvimInvalidAugmentedAssignment" })
	hi("NvimInvalidAssignmentWithSubtraction", { link = "NvimInvalidAugmentedAssignment" })
	hi("NvimInvalidAugmentedAssignment", { link = "NvimInvalidAssignment" })
	hi("NvimInvalidBinaryMinus", { link = "NvimInvalidBinaryOperator" })
	hi("NvimInvalidBinaryOperator", { link = "NvimInvalidOperator" })
	hi("NvimInvalidBinaryPlus", { link = "NvimInvalidBinaryOperator" })
	hi("NvimInvalidCallingParenthesis", { link = "NvimInvalidParenthesis" })
	hi("NvimInvalidColon", { link = "NvimInvalidDelimiter" })
	hi("NvimInvalidComma", { link = "NvimInvalidDelimiter" })
	hi("NvimInvalidComparison", { link = "NvimInvalidBinaryOperator" })
	hi("NvimInvalidComparisonModifier", { link = "NvimInvalidComparison" })
	hi("NvimInvalidConcat", { link = "NvimInvalidBinaryOperator" })
	hi("NvimInvalidConcatOrSubscript", { link = "NvimInvalidConcat" })
	hi("NvimInvalidContainer", { link = "NvimInvalidParenthesis" })
	hi("NvimInvalidCurly", { link = "NvimInvalidSubscript" })
	hi("NvimInvalidDelimiter", { link = "NvimInvalid" })
	hi("NvimInvalidDict", { link = "NvimInvalidContainer" })
	hi("NvimInvalidDivision", { link = "NvimInvalidBinaryOperator" })
	hi("NvimInvalidDoubleQuote", { link = "NvimInvalidStringQuote" })
	hi("NvimInvalidDoubleQuotedBody", { link = "NvimInvalidStringBody" })
	hi("NvimInvalidDoubleQuotedEscape", { link = "NvimInvalidStringSpecial" })
	hi("NvimInvalidDoubleQuotedUnknownEscape", { link = "NvimInvalidValue" })
	hi("NvimInvalidEnvironmentName", { link = "NvimInvalidIdentifier" })
	hi("NvimInvalidEnvironmentSigil", { link = "NvimInvalidOptionSigil" })
	hi("NvimInvalidFigureBrace", { link = "NvimInvalidDelimiter" })
	hi("NvimInvalidFloat", { link = "NvimInvalidNumber" })
	hi("NvimInvalidIdentifier", { link = "NvimInvalidValue" })
	hi("NvimInvalidIdentifierKey", { link = "NvimInvalidIdentifier" })
	hi("NvimInvalidIdentifierName", { link = "NvimInvalidIdentifier" })
	hi("NvimInvalidIdentifierScope", { link = "NvimInvalidIdentifier" })
	hi("NvimInvalidIdentifierScopeDelimiter", { link = "NvimInvalidIdentifier" })
	hi("NvimInvalidLambda", { link = "NvimInvalidParenthesis" })
	hi("NvimInvalidList", { link = "NvimInvalidContainer" })
	hi("NvimInvalidMod", { link = "NvimInvalidBinaryOperator" })
	hi("NvimInvalidMultiplication", { link = "NvimInvalidBinaryOperator" })
	hi("NvimInvalidNestingParenthesis", { link = "NvimInvalidParenthesis" })
	hi("NvimInvalidNot", { link = "NvimInvalidUnaryOperator" })
	hi("NvimInvalidNumber", { link = "NvimInvalidValue" })
	hi("NvimInvalidNumberPrefix", { link = "NvimInvalidNumber" })
	hi("NvimInvalidOperator", { link = "NvimInvalid" })
	hi("NvimInvalidOptionName", { link = "NvimInvalidIdentifier" })
	hi("NvimInvalidOptionScope", { link = "NvimInvalidIdentifierScope" })
	hi("NvimInvalidOptionScopeDelimiter", { link = "NvimInvalidIdentifierScopeDelimiter" })
	hi("NvimInvalidOptionSigil", { link = "NvimInvalidIdentifier" })
	hi("NvimInvalidOr", { link = "NvimInvalidBinaryOperator" })
	hi("NvimInvalidParenthesis", { link = "NvimInvalidDelimiter" })
	hi("NvimInvalidPlainAssignment", { link = "NvimInvalidAssignment" })
	hi("NvimInvalidRegister", { link = "NvimInvalidValue" })
	hi("NvimInvalidSingleQuote", { link = "NvimInvalidStringQuote" })
	hi("NvimInvalidSingleQuotedBody", { link = "NvimInvalidStringBody" })
	hi("NvimInvalidSingleQuotedQuote", { link = "NvimInvalidStringSpecial" })
	hi("NvimInvalidSingleQuotedUnknownEscape", { link = "NvimInternalError" })
	hi("NvimInvalidSpacing", { link = "ErrorMsg" })
	hi("NvimInvalidString", { link = "NvimInvalidValue" })
	hi("NvimInvalidStringBody", { link = "NvimStringBody" })
	hi("NvimInvalidStringQuote", { link = "NvimInvalidString" })
	hi("NvimInvalidStringSpecial", { link = "NvimStringSpecial" })
	hi("NvimInvalidSubscript", { link = "NvimInvalidParenthesis" })
	hi("NvimInvalidSubscriptBracket", { link = "NvimInvalidSubscript" })
	hi("NvimInvalidSubscriptColon", { link = "NvimInvalidSubscript" })
	hi("NvimInvalidTernary", { link = "NvimInvalidOperator" })
	hi("NvimInvalidTernaryColon", { link = "NvimInvalidTernary" })
	hi("NvimInvalidUnaryMinus", { link = "NvimInvalidUnaryOperator" })
	hi("NvimInvalidUnaryOperator", { link = "NvimInvalidOperator" })
	hi("NvimInvalidUnaryPlus", { link = "NvimInvalidUnaryOperator" })
	hi("NvimInvalidValue", { link = "NvimInvalid" })
	hi("NvimLambda", { link = "NvimParenthesis" })
	hi("NvimList", { link = "NvimContainer" })
	hi("NvimMod", { link = "NvimBinaryOperator" })
	hi("NvimMultiplication", { link = "NvimBinaryOperator" })
	hi("NvimNestingParenthesis", { link = "NvimParenthesis" })
	hi("NvimNot", { link = "NvimUnaryOperator" })
	hi("NvimNumber", { link = "Number" })
	hi("NvimNumberPrefix", { link = "Type" })
	hi("NvimOperator", { link = "Operator" })
	hi("NvimOptionName", { link = "NvimIdentifier" })
	hi("NvimOptionScope", { link = "NvimIdentifierScope" })
	hi("NvimOptionScopeDelimiter", { link = "NvimIdentifierScopeDelimiter" })
	hi("NvimOptionSigil", { link = "Type" })
	hi("NvimOr", { link = "NvimBinaryOperator" })
	hi("NvimParenthesis", { link = "Delimiter" })
	hi("NvimPlainAssignment", { link = "NvimAssignment" })
	hi("NvimRegister", { link = "SpecialChar" })
	hi("NvimSingleQuote", { link = "NvimStringQuote" })
	hi("NvimSingleQuotedBody", { link = "NvimStringBody" })
	hi("NvimSingleQuotedQuote", { link = "NvimStringSpecial" })
	hi("NvimSingleQuotedUnknownEscape", { link = "NvimInternalError" })
	hi("NvimSpacing", { link = "Normal" })
	hi("NvimString", { link = "String" })
	hi("NvimStringBody", { link = "NvimString" })
	hi("NvimStringQuote", { link = "NvimString" })
	hi("NvimStringSpecial", { link = "SpecialChar" })
	hi("NvimSubscript", { link = "NvimParenthesis" })
	hi("NvimSubscriptBracket", { link = "NvimSubscript" })
	hi("NvimSubscriptColon", { link = "NvimSubscript" })
	hi("NvimTernary", { link = "NvimOperator" })
	hi("NvimTernaryColon", { link = "NvimTernary" })
	hi("NvimUnaryMinus", { link = "NvimUnaryOperator" })
	hi("NvimUnaryOperator", { link = "NvimOperator" })
	hi("NvimUnaryPlus", { link = "NvimUnaryOperator" })
	hi("PmenuBorder", { link = "Pmenu" })
	hi("PmenuExtra", { link = "Pmenu" })
	hi("PmenuExtraSel", { link = "PmenuSel" })
	hi("PmenuKind", { link = "Pmenu" })
	hi("PmenuKindSel", { link = "PmenuSel" })
	hi("PmenuMatch", { cterm = { bold = true }, bold = true })
	hi("PmenuMatchSel", { cterm = { bold = true }, bold = true })
	hi("PmenuSbar", { link = "Pmenu" })
	hi("PmenuSel", { cterm = { underline = true, reverse = true }, reverse = true, blend = 0 })
	hi("PmenuShadow", { link = "FloatShadow" })
	hi("PmenuShadowThrough", { link = "FloatShadowThrough" })
	hi("PreCondit", { link = "PreProc" })
	hi("PreInsert", { link = "Added" })
	hi("RedrawDebugNormal", { cterm = { reverse = true }, reverse = true })
	hi("Repeat", { link = "Statement" })
	hi("SnippetTabstop", { link = "Visual" })
	hi("SnippetTabstopActive", { link = "SnippetTabstop" })
	hi("SpecialChar", { link = "Special" })
	hi("SpecialComment", { link = "Special" })
	hi("SpecialKey", { link = "Special" })
	hi("StatusLineTerm", { link = "StatusLine" })
	hi("StatusLineTermNC", { link = "StatusLineNC" })
	hi("StderrMsg", { link = "ErrorMsg" })
	hi("StdoutMsg", {  })
	hi("StorageClass", { link = "Type" })
	hi("Structure", { link = "Type" })
	hi("Substitute", { link = "Search" })
	hi("TabLine", { link = "StatusLineNC" })
	hi("TabLineFill", { link = "TabLine" })
	hi("TabLineSel", { cterm = {  }, bold = true })
	hi("Tag", { link = "Special" })
	hi("TermCursor", { cterm = { reverse = true }, reverse = true })
	hi("Typedef", { link = "Type" })
	hi("Underlined", { cterm = { underline = true }, underline = true })
	hi("VertSplit", { link = "WinSeparator" })
	hi("VisualNOS", { link = "Visual" })
	hi("Whitespace", { link = "NonText" })
	hi("WildMenu", { link = "PmenuSel" })
	hi("WinSeparator", { link = "Normal" })
end

-- Highlight groups from Neovim's light default.
local function apply_light_highlights()
	hi("@markup.heading.1.delimiter.vimdoc", { fg = c.OldFaithfulLightGrey2, bg = c.OldFaithfulLightGrey2, sp = c.OldFaithfulDarkGrey2, cterm = { underdouble = true, nocombine = true }, underdouble = true, nocombine = true })
	hi("@markup.heading.2.delimiter.vimdoc", { fg = c.OldFaithfulLightGrey2, bg = c.OldFaithfulLightGrey2, sp = c.OldFaithfulDarkGrey2, cterm = { underline = true, nocombine = true }, underline = true, nocombine = true })
	hi("@variable", { fg = c.OldFaithfulDarkGrey2 })
	hi("Added", { fg = c.OldFaithfulDarkGreen, ctermfg = 22 })
	hi("Changed", { fg = c.OldFaithfulDarkCyan, ctermfg = 30 })
	hi("ColorColumn", { bg = c.OldFaithfulLightGrey4, cterm = { reverse = true } })
	hi("Comment", { fg = c.OldFaithfulDarkGrey4 })
	hi("Conceal", { fg = c.OldFaithfulLightGrey4 })
	hi("Constant", { fg = c.OldFaithfulDarkGrey2 })
	hi("CurSearch", { fg = c.OldFaithfulLightGrey1, bg = c.OldFaithfulDarkYellow, ctermfg = 255, ctermbg = 58 })
	hi("Cursor", { fg = c.OldFaithfulLightGrey2, bg = c.OldFaithfulDarkGrey2 })
	hi("CursorColumn", { bg = c.OldFaithfulLightGrey3 })
	hi("CursorLine", { bg = c.OldFaithfulLightGrey3 })
	hi("Delimiter", { fg = c.OldFaithfulDarkGrey2 })
	hi("DiagnosticDeprecated", { sp = c.OldFaithfulDarkRed, cterm = { strikethrough = true }, strikethrough = true })
	hi("DiagnosticError", { fg = c.OldFaithfulDarkRed, ctermfg = 52 })
	hi("DiagnosticHint", { fg = c.OldFaithfulDarkBlue, ctermfg = 24 })
	hi("DiagnosticInfo", { fg = c.OldFaithfulDarkCyan, ctermfg = 30 })
	hi("DiagnosticOk", { fg = c.OldFaithfulDarkGreen, ctermfg = 22 })
	hi("DiagnosticUnderlineError", { sp = c.OldFaithfulDarkRed, cterm = { underline = true }, underline = true })
	hi("DiagnosticUnderlineHint", { sp = c.OldFaithfulDarkBlue, cterm = { underline = true }, underline = true })
	hi("DiagnosticUnderlineInfo", { sp = c.OldFaithfulDarkCyan, cterm = { underline = true }, underline = true })
	hi("DiagnosticUnderlineOk", { sp = c.OldFaithfulDarkGreen, cterm = { underline = true }, underline = true })
	hi("DiagnosticUnderlineWarn", { sp = c.OldFaithfulDarkYellow, cterm = { underline = true }, underline = true })
	hi("DiagnosticWarn", { fg = c.OldFaithfulDarkYellow, ctermfg = 58 })
	hi("DiffAdd", { fg = c.OldFaithfulDarkGrey1, bg = c.OldFaithfulLightGreen, ctermfg = 232, ctermbg = 41 })
	hi("DiffChange", { fg = c.OldFaithfulDarkGrey1, bg = c.OldFaithfulLightGrey4 })
	hi("DiffDelete", { fg = c.OldFaithfulDarkRed, ctermfg = 52, cterm = { bold = true }, bold = true })
	hi("DiffText", { fg = c.OldFaithfulDarkGrey1, bg = c.OldFaithfulLightCyan, ctermfg = 232, ctermbg = 44 })
	hi("Directory", { fg = c.OldFaithfulDarkCyan, ctermfg = 30 })
	hi("Error", { fg = c.OldFaithfulDarkGrey1, bg = c.OldFaithfulLightRed, ctermfg = 232, ctermbg = 203 })
	hi("ErrorMsg", { fg = c.OldFaithfulDarkRed, ctermfg = 52 })
	hi("FloatShadow", { bg = c.OldFaithfulLightGrey4, ctermbg = 247, blend = 80 })
	hi("FloatShadowThrough", { bg = c.OldFaithfulLightGrey4, ctermbg = 247, blend = 100 })
	hi("Folded", { fg = c.OldFaithfulDarkGrey4, bg = c.OldFaithfulLightGrey1 })
	hi("Function", { fg = c.OldFaithfulDarkCyan, ctermfg = 30 })
	hi("Identifier", { fg = c.OldFaithfulDarkBlue, ctermfg = 24 })
	hi("LineNr", { fg = c.OldFaithfulLightGrey4 })
	hi("MatchParen", { bg = c.OldFaithfulLightGrey4, cterm = { bold = true, underline = true }, bold = true })
	hi("ModeMsg", { fg = c.OldFaithfulDarkGreen, ctermfg = 22 })
	hi("MoreMsg", { fg = c.OldFaithfulDarkCyan, ctermfg = 30 })
	hi("NonText", { fg = c.OldFaithfulLightGrey4 })
	hi("Normal", { fg = c.OldFaithfulDarkGrey2, bg = c.OldFaithfulLightGrey2 })
	hi("NormalFloat", { bg = c.OldFaithfulLightGrey1 })
	hi("OkMsg", { fg = c.OldFaithfulDarkGreen, ctermfg = 22 })
	hi("Operator", { fg = c.OldFaithfulDarkGrey2 })
	hi("Pmenu", { bg = c.OldFaithfulLightGrey3, cterm = { reverse = true } })
	hi("PmenuThumb", { bg = c.OldFaithfulLightGrey4 })
	hi("PreProc", { fg = c.OldFaithfulDarkGrey2 })
	hi("Question", { fg = c.OldFaithfulDarkCyan, ctermfg = 30 })
	hi("QuickFixLine", { fg = c.OldFaithfulDarkCyan, ctermfg = 30 })
	hi("RedrawDebugClear", { bg = c.OldFaithfulLightYellow, ctermfg = 15, ctermbg = 214 })
	hi("RedrawDebugComposed", { bg = c.OldFaithfulLightGreen, ctermfg = 15, ctermbg = 41 })
	hi("RedrawDebugRecompose", { bg = c.OldFaithfulLightRed, ctermfg = 15, ctermbg = 203 })
	hi("Removed", { fg = c.OldFaithfulDarkRed, ctermfg = 52 })
	hi("Search", { fg = c.OldFaithfulDarkGrey1, bg = c.OldFaithfulLightYellow, ctermfg = 232, ctermbg = 214 })
	hi("SignColumn", { fg = c.OldFaithfulLightGrey4 })
	hi("Special", { fg = c.OldFaithfulDarkCyan, ctermfg = 30 })
	hi("SpellBad", { sp = c.OldFaithfulDarkRed, cterm = { undercurl = true }, undercurl = true })
	hi("SpellCap", { sp = c.OldFaithfulDarkYellow, cterm = { undercurl = true }, undercurl = true })
	hi("SpellLocal", { sp = c.OldFaithfulDarkGreen, cterm = { undercurl = true }, undercurl = true })
	hi("SpellRare", { sp = c.OldFaithfulDarkCyan, cterm = { undercurl = true }, undercurl = true })
	hi("Statement", { fg = c.OldFaithfulDarkGrey2, cterm = { bold = true }, bold = true })
	hi("StatusLine", { fg = c.OldFaithfulDarkGrey2, bg = c.OldFaithfulLightGrey4, cterm = { reverse = true } })
	hi("StatusLineNC", { fg = c.OldFaithfulDarkGrey3, bg = c.OldFaithfulLightGrey3, cterm = { bold = true, underline = true } })
	hi("String", { fg = c.OldFaithfulDarkGreen, ctermfg = 22 })
	hi("Title", { fg = c.OldFaithfulDarkGrey2, cterm = { bold = true }, bold = true })
	hi("Todo", { fg = c.OldFaithfulDarkGrey2, cterm = { bold = true }, bold = true })
	hi("Type", { fg = c.OldFaithfulDarkGrey2 })
	hi("Visual", { bg = c.OldFaithfulLightGrey4, ctermfg = 15, ctermbg = 247 })
	hi("WarningMsg", { fg = c.OldFaithfulDarkYellow, ctermfg = 58 })
	hi("WinBar", { fg = c.OldFaithfulDarkGrey4, bg = c.OldFaithfulLightGrey1, cterm = { bold = true }, bold = true })
	hi("WinBarNC", { fg = c.OldFaithfulDarkGrey4, bg = c.OldFaithfulLightGrey1, cterm = { bold = true } })
	hi("lCursor", { fg = c.OldFaithfulLightGrey2, bg = c.OldFaithfulDarkGrey2 })
end

-- Highlight groups from Neovim's dark default.
local function apply_dark_highlights()
	hi("@markup.heading.1.delimiter.vimdoc", { fg = c.OldFaithfulDarkGrey2, bg = c.OldFaithfulDarkGrey2, sp = c.OldFaithfulLightGrey2, cterm = { underdouble = true, nocombine = true }, underdouble = true, nocombine = true })
	hi("@markup.heading.2.delimiter.vimdoc", { fg = c.OldFaithfulDarkGrey2, bg = c.OldFaithfulDarkGrey2, sp = c.OldFaithfulLightGrey2, cterm = { underline = true, nocombine = true }, underline = true, nocombine = true })
	hi("@variable", { fg = c.OldFaithfulLightGrey2 })
	hi("Added", { fg = c.OldFaithfulLightGreen, ctermfg = 41 })
	hi("Changed", { fg = c.OldFaithfulLightCyan, ctermfg = 44 })
	hi("ColorColumn", { bg = c.OldFaithfulDarkGrey4, cterm = { reverse = true } })
	hi("Comment", { fg = c.OldFaithfulLightGrey4 })
	hi("Conceal", { fg = c.OldFaithfulDarkGrey4 })
	hi("Constant", { fg = c.OldFaithfulLightGrey2 })
	hi("CurSearch", { fg = c.OldFaithfulDarkGrey1, bg = c.OldFaithfulLightYellow, ctermfg = 232, ctermbg = 214 })
	hi("Cursor", { fg = c.OldFaithfulDarkGrey2, bg = c.OldFaithfulLightGrey2 })
	hi("CursorColumn", { bg = c.OldFaithfulDarkGrey3 })
	hi("CursorLine", { bg = c.OldFaithfulDarkGrey3 })
	hi("Delimiter", { fg = c.OldFaithfulLightGrey2 })
	hi("DiagnosticDeprecated", { sp = c.OldFaithfulLightRed, cterm = { strikethrough = true }, strikethrough = true })
	hi("DiagnosticError", { fg = c.OldFaithfulLightRed, ctermfg = 203 })
	hi("DiagnosticHint", { fg = c.OldFaithfulLightBlue, ctermfg = 69 })
	hi("DiagnosticInfo", { fg = c.OldFaithfulLightCyan, ctermfg = 44 })
	hi("DiagnosticOk", { fg = c.OldFaithfulLightGreen, ctermfg = 41 })
	hi("DiagnosticUnderlineError", { sp = c.OldFaithfulLightRed, cterm = { underline = true }, underline = true })
	hi("DiagnosticUnderlineHint", { sp = c.OldFaithfulLightBlue, cterm = { underline = true }, underline = true })
	hi("DiagnosticUnderlineInfo", { sp = c.OldFaithfulLightCyan, cterm = { underline = true }, underline = true })
	hi("DiagnosticUnderlineOk", { sp = c.OldFaithfulLightGreen, cterm = { underline = true }, underline = true })
	hi("DiagnosticUnderlineWarn", { sp = c.OldFaithfulLightYellow, cterm = { underline = true }, underline = true })
	hi("DiagnosticWarn", { fg = c.OldFaithfulLightYellow, ctermfg = 214 })
	hi("DiffAdd", { fg = c.OldFaithfulLightGrey1, bg = c.OldFaithfulDarkGreen, ctermfg = 255, ctermbg = 22 })
	hi("DiffChange", { fg = c.OldFaithfulLightGrey1, bg = c.OldFaithfulDarkGrey4 })
	hi("DiffDelete", { fg = c.OldFaithfulLightRed, ctermfg = 203, cterm = { bold = true }, bold = true })
	hi("DiffText", { fg = c.OldFaithfulLightGrey1, bg = c.OldFaithfulDarkCyan, ctermfg = 255, ctermbg = 30 })
	hi("Directory", { fg = c.OldFaithfulLightCyan, ctermfg = 44 })
	hi("Error", { fg = c.OldFaithfulLightGrey1, bg = c.OldFaithfulDarkRed, ctermfg = 255, ctermbg = 52 })
	hi("ErrorMsg", { fg = c.OldFaithfulLightRed, ctermfg = 203 })
	hi("FloatShadow", { bg = c.OldFaithfulDarkGrey4, ctermbg = 239, blend = 80 })
	hi("FloatShadowThrough", { bg = c.OldFaithfulDarkGrey4, ctermbg = 239, blend = 100 })
	hi("Folded", { fg = c.OldFaithfulLightGrey4, bg = c.OldFaithfulDarkGrey1 })
	hi("Function", { fg = c.OldFaithfulLightCyan, ctermfg = 44 })
	hi("Identifier", { fg = c.OldFaithfulLightBlue, ctermfg = 69 })
	hi("LineNr", { fg = c.OldFaithfulDarkGrey4 })
	hi("MatchParen", { bg = c.OldFaithfulDarkGrey4, cterm = { bold = true, underline = true }, bold = true })
	hi("ModeMsg", { fg = c.OldFaithfulLightGreen, ctermfg = 41 })
	hi("MoreMsg", { fg = c.OldFaithfulLightCyan, ctermfg = 44 })
	hi("NonText", { fg = c.OldFaithfulDarkGrey4 })
	hi("Normal", { fg = c.OldFaithfulLightGrey2, bg = c.OldFaithfulDarkGrey2 })
	hi("NormalFloat", { bg = c.OldFaithfulDarkGrey1 })
	hi("OkMsg", { fg = c.OldFaithfulLightGreen, ctermfg = 41 })
	hi("Operator", { fg = c.OldFaithfulLightGrey2 })
	hi("Pmenu", { bg = c.OldFaithfulDarkGrey3, cterm = { reverse = true } })
	hi("PmenuThumb", { bg = c.OldFaithfulDarkGrey4 })
	hi("PreProc", { fg = c.OldFaithfulLightGrey2 })
	hi("Question", { fg = c.OldFaithfulLightCyan, ctermfg = 44 })
	hi("QuickFixLine", { fg = c.OldFaithfulLightCyan, ctermfg = 44 })
	hi("RedrawDebugClear", { bg = c.OldFaithfulDarkYellow, ctermfg = 0, ctermbg = 58 })
	hi("RedrawDebugComposed", { bg = c.OldFaithfulDarkGreen, ctermfg = 0, ctermbg = 22 })
	hi("RedrawDebugRecompose", { bg = c.OldFaithfulDarkRed, ctermfg = 0, ctermbg = 52 })
	hi("Removed", { fg = c.OldFaithfulLightRed, ctermfg = 203 })
	hi("Search", { fg = c.OldFaithfulLightGrey1, bg = c.OldFaithfulDarkYellow, ctermfg = 255, ctermbg = 58 })
	hi("SignColumn", { fg = c.OldFaithfulDarkGrey4 })
	hi("Special", { fg = c.OldFaithfulLightCyan, ctermfg = 44 })
	hi("SpellBad", { sp = c.OldFaithfulLightRed, cterm = { undercurl = true }, undercurl = true })
	hi("SpellCap", { sp = c.OldFaithfulLightYellow, cterm = { undercurl = true }, undercurl = true })
	hi("SpellLocal", { sp = c.OldFaithfulLightGreen, cterm = { undercurl = true }, undercurl = true })
	hi("SpellRare", { sp = c.OldFaithfulLightCyan, cterm = { undercurl = true }, undercurl = true })
	hi("Statement", { fg = c.OldFaithfulLightGrey2, cterm = { bold = true }, bold = true })
	hi("StatusLine", { fg = c.OldFaithfulLightGrey2, bg = c.OldFaithfulDarkGrey4, cterm = { reverse = true } })
	hi("StatusLineNC", { fg = c.OldFaithfulLightGrey3, bg = c.OldFaithfulDarkGrey3, cterm = { bold = true, underline = true } })
	hi("String", { fg = c.OldFaithfulLightGreen, ctermfg = 41 })
	hi("Title", { fg = c.OldFaithfulLightGrey2, cterm = { bold = true }, bold = true })
	hi("Todo", { fg = c.OldFaithfulLightGrey2, cterm = { bold = true }, bold = true })
	hi("Type", { fg = c.OldFaithfulLightGrey2 })
	hi("Visual", { bg = c.OldFaithfulDarkGrey4, ctermfg = 0, ctermbg = 239 })
	hi("WarningMsg", { fg = c.OldFaithfulLightYellow, ctermfg = 214 })
	hi("WinBar", { fg = c.OldFaithfulLightGrey4, bg = c.OldFaithfulDarkGrey1, cterm = { bold = true }, bold = true })
	hi("WinBarNC", { fg = c.OldFaithfulLightGrey4, bg = c.OldFaithfulDarkGrey1, cterm = { bold = true } })
	hi("lCursor", { fg = c.OldFaithfulDarkGrey2, bg = c.OldFaithfulLightGrey2 })
end

apply_common_highlights()

if vim.o.background == "light" then
	apply_light_highlights()
else
	apply_dark_highlights()
end

palette.apply_color_highlights()

vim.g.terminal_color_0 = c.OldFaithfulDarkGrey2
vim.g.terminal_color_1 = c.OldFaithfulLightRed
vim.g.terminal_color_2 = c.OldFaithfulLightGreen
vim.g.terminal_color_3 = c.OldFaithfulLightYellow
vim.g.terminal_color_4 = c.OldFaithfulLightBlue
vim.g.terminal_color_5 = c.OldFaithfulLightMagenta
vim.g.terminal_color_6 = c.OldFaithfulLightCyan
vim.g.terminal_color_7 = c.OldFaithfulLightGrey1
vim.g.terminal_color_8 = c.OldFaithfulDarkGrey4
vim.g.terminal_color_9 = c.OldFaithfulLightRed
vim.g.terminal_color_10 = c.OldFaithfulLightGreen
vim.g.terminal_color_11 = c.OldFaithfulLightYellow
vim.g.terminal_color_12 = c.OldFaithfulLightBlue
vim.g.terminal_color_13 = c.OldFaithfulLightMagenta
vim.g.terminal_color_14 = c.OldFaithfulLightCyan
vim.g.terminal_color_15 = "#ffffff"

